### ISSUE TITLE
How to insert a placeholder in the translated values?

### ISSUE THREAD

**Issue by vinnytwice** [billylev/flutter_localizations#1]
I'm porting my Swift app to Flutter and for localising it I'm following this guide but I can't see how to insert placeholder to insert a value in the translated values. 
Basically I see the guide uses 

    String text(String key) {
        return _localisedValues[key] ?? "$key not found";
      } 

to get the corresponding key:value pair from a .json file as 

    {
      "Shop": "Negozio",
    }

I just pass it in the `Text`widget as :

`Text(AppLocalizations.instance.text('Shop'))`.

How to modify `text` to insert one or more placeholders and how would be the .json be constructed? 
Say for the value `"User": "User"` I'd like to insert a value after the transaction I can simply use a string sum and add the value as `Text(AppLocalizations.instance.text('User') + ' ${widget.user.name}'`, but if I need to insert a value in the middle of the translated sentence, eg a message, I don't see how to accomplish it.
I need it to make localised versions of incoming push notification, and they have args.

In Swift I have it like this:

```
    "ORDER_RECEIVED_PUSH_TITLE" = "Order number: %@";
    "ORDER_RECEIVED_PUSH_SUBTITLE" = "Shop: %@";
    "ORDER_RECEIVED_PUSH_BODY" = "Thank you %@! We received your order and we'll let you know when we start preparing it and when it's ready. Bye";
```

Any suggestions on how to accomplish that in Flutter?

Many thanks

**Comment by billylev** [comment]
Have a look at the sprintf package in Dart. See https://developermemos.com/posts/using-sprintf-flutter-dart, for an explanation.  Once you have added the package, you can do the following

`"ORDER_RECEIVED_PUSH_BODY" = "Thank you %s! We received your order and we'll let you know when we start preparing it and when it's ready. Bye";`

`Text(sprintf(AppLocalizations.instance.text('ORDER_RECEIVED_PUSH_BODY'), ["Bob"])`

**Comment by vinnytwice** [comment]
@billylev Thanks. My problem is that strings like `"ORDER_RECEIVED_PUSH_TITLE" = "Order number: %@";` have to live in a json file used for translation. With the push I would just receive `ORDER_RECEIVED_PUSH_TITLE` together with args then the localization would output the message in the correct language. So I need a place holder in the json.. something like 
```
{
 "ORDER_RECEIVED_PUSH_TITLE" : "Order number {}";
}
```
I'm having a look at the sample projects and it seems that  it is just the way it works..

**Comment by billylev** [comment]
@vinnytwice, I still think sprintf is what you want, in the json you would put

```
{
  "title": "Localization Demo",
  "page_one": "Page %s %s",
  "page_two": "Page two",
  "page_three": "Page three"
}

class DashboardPage1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const textBody = 'page_one';
    const parm1 = 'abc';
    const parm2 = 'xyz';

    return Container(
        child: new Center(
      child: new Text(
        sprintf(AppLocalizations.instance.text(textBody), [parm1, parm2]),
        style: new TextStyle(
          fontSize: 22.00,
          fontWeight: FontWeight.bold,
        ),
      ),
    ));
  }
}
```

This will draw the text 'Page abc xyz' on the page.

**Comment by vinnytwice** [comment]
@billylev wow that's great. Indeed what I need! Thank you so much!
