### ISSUE TITLE
Nested json files are supported?

### ISSUE THREAD

**Issue by glatrofa** [billylev/flutter_localizations#4]
Hi, first of all **thank you** for this code.
It's possible to access nested json files? Like this one:
```json
{
"file1_strings": {
            "key1": "value1",
            "key2": "value2"
           },
"file2_strings": {
            "key1": "value1",
            "key2": "value2"
           }
}
```
In this way is possible to have all the translated strings in a single place. This can be is an easiest way to manage the translations between multiple files.

**Comment by billylev** [comment]
Yes you could change the code for the AppLocalizations to handle that

**Comment by glatrofa** [comment]
Great, thanks!
So in this way is possible accessing keys in a single .json file (which contains strings of a single language) which are organized per file where are used:
```dart
String text(String fileName, String key) {
    return _localisedValues[fileName][key] ?? "$key not found";
}
```
